FROM nginx:alpine

# Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*
# Copy NGINX default server configuration
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
# Copy built frontend files
COPY apps/product-quotation/dist/ /usr/share/nginx/html/
